version: '3.8'

services:
  db:
    container_name: Calculator_database
    image: postgres:14.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
    volumes:
      - ./volumes/postgresql-data:/var/lib/postgresql/data


  web:
    container_name: Calculator_localapp
    image: grabe85me/docker_calculator:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db