version: '3.8'

services:
  db:
    image: postgres:14.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
    networks:
      - web
      - db


  web:
    depends_on:
      - db
    image: grabe85me/docker_calculator:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - db
      - web

networks:
  db:
  web: